version: '3'

services:
  react:
    build: .
    container_name: react
    restart: always
    hostname: gateway
    env_file:
      - ../.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
